### ISSUE TITLE
add hook to do pre-processing of events before writing to disk

### ISSUE THREAD

**Issue by licode** [NSLS-II/suitcase#35]
Also beamline_id keyward is not always included at run start. We may need to modify the part where saving with beamline_id is used.

**Comment by danielballan** [comment]
The scope of suitcase packages is now strictly: "You give me documents and a transport mechanism; I serialize the documents into bytes and push them into that transport mechanism." Pre-processing should be done upstream by modifying the documents before they reach the Serializer.
