### ISSUE TITLE
List of formats to write suitcases for

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/suitcase#52]
This is a tracking issue.

- [ ] CSV (@awalter-bnl)
- [ ] TIFF (@awalter-bnl)
- [ ] JSON (@awalter-bnl)
- [ ] Nexus Archive (@awalter-bnl and @stuartcampbell)
- [ ] BSON
- [ ] mongo
- [ ] specfile
- [ ] Athena (to be delegated to Bruce once CSV/TIFF/JSON are in good shape as examples)
- [ ] XAFS Data Interchange (doi:10.1088/1742-6596/712/1/012148)
- [ ] [DataExchange](https://www.aps.anl.gov/Science/Scientific-Software/DataExchange) 
- [ ] CBOR

Also, a straight "give me a copy of the files as they are presently serialized" would be useful.

**Comment by awalter-bnl** [comment]
@danielballan I am also happy to take on BSON once  JSON is done as it will be pretty similar.

**Comment by danielballan** [comment]
Thanks, @awalter-bnl.

**Comment by stuartcampbell** [comment]
I've added another format to the list - and some refs/links

**Comment by danielballan** [comment]
All of these are now captured in the documentation at https://nsls-ii.github.io/suitcase/formats.html

I am going to close this and suggest that we track new planned/request formats by putting PRs against the documentation so that we have one place to look, and a place that the community can easily find.
