### ISSUE TITLE
suitcase not working in CSX-1 notebook - USERS cannot extract data

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/suitcase#7]
FILENAME = 'my_data'  # no file extension; we take care of that below
SCAN_ID = 50934
OVERWRITE = True  # If true, I will delete the file FILENAME if it exists.
In [12]:

from dataportal import DataBroker as db
import os
from suitcase import export
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-f7d33868b431> in <module>()
      1 from dataportal import DataBroker as db
      2 import os
----> 3 from suitcase import export

ImportError: No module named 'suitcase'

In [13]:

# sanity check that we can see the GPFS. If this fails, give up and email Rob Petkus. There is no hope.
!ls '/GPFS/'
xf23id
In [16]:

h = db[SCAN_ID]
h
Out[16]:
descriptors	[{'run_start': '85e04a15-1072-4714-814d-76f0ec9edb87', 'time_as_datetime': datetime.datetime(2015, 7, 27, 9, 13, 59, 361000), '_name': 'EventDescriptor', 'time': 1438002839.361421, 'data_keys': {'theta': {'source': 'PV:XF:23ID1-ES{Dif-Ax:Th}Mtr.RBV', 'dtype': 'number', 'shape': []}, 'sz': {'source': 'PV:XF:23ID1-ES{Dif-Ax:SZ}Pos-RB', 'dtype': 'number', 'shape': []}, 'sclr_chan1': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S1', 'dtype': 'number', 'shape': []}, 'sclr_chan2': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S2', 'dtype': 'number', 'shape': []}, 'delta': {'source': 'PV:XF:23ID1-ES{Dif-Ax:Del}Mtr.RBV', 'dtype': 'number', 'shape': []}, 'fccd_image_lightfield': {'external': 'FILESTORE:', 'source': 'PV:XF:23ID1-ES{FCCD}', 'dtype': 'array', 'shape': [26, 960, 960]}, 'sy': {'source': 'PV:XF:23ID1-ES{Dif-Ax:SY}Pos-RB', 'dtype': 'number', 'shape': []}, 'fccd_acquire_period': {'source': 'PV:XF:23ID1-ES{FCCD}cam1:AcquirePeriod_RBV', 'dtype': 'number', 'shape': []}, 'sclr_chan5': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S5', 'dtype': 'number', 'shape': []}, 'temp_a': {'source': 'PV:XF:23ID1-ES{TCtrl:1-Chan:A}T-I', 'dtype': 'number', 'shape': []}, 'pgm_energy': {'source': 'PV:XF:23ID1-OP{Mono}Enrgy-I', 'dtype': 'number', 'shape': []}, 'temp_b': {'source': 'PV:XF:23ID1-ES{TCtrl:1-Chan:B}T-I', 'dtype': 'number', 'shape': []}, 'sclr_chan4': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S4', 'dtype': 'number', 'shape': []}, 'saz': {'source': 'PV:XF:23ID1-ES{Dif-Ax:Z}Mtr.RBV', 'dtype': 'number', 'shape': []}, 'sclr_chan3': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S3', 'dtype': 'number', 'shape': []}, 'sclr_chan6': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S6', 'dtype': 'number', 'shape': []}, 'sclr_time': {'source': 'PV:XF:23ID1-ES{Sclr:1}.T', 'dtype': 'number', 'shape': []}, 'gamma': {'source': 'PV:XF:23ID1-ES{Dif-Ax:Gam}Mtr.RBV', 'dtype': 'number', 'shape': []}, 'sclr_chan7': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S7', 'dtype': 'number', 'shape': []}, 'fccd_acquire_time': {'source': 'PV:XF:23ID1-ES{FCCD}cam1:AcquireTime_RBV', 'dtype': 'number', 'shape': []}, 'sclr_chan8': {'source': 'PV:XF:23ID1-ES{Sclr:1}.S8', 'dtype': 'number', 'shape': []}, 'epu2_gap': {'source': 'PV:XF:23ID-ID{EPU:2-Ax:Gap}Pos-I', 'dtype': 'number', 'shape': []}, 'sx': {'source': 'PV:XF:23ID1-ES{Dif-Ax:X}Mtr.RBV', 'dtype': 'number', 'shape': []}, 'say': {'source': 'PV:XF:23ID1-ES{Dif-Ax:Y}Mtr.RBV', 'dtype': 'number', 'shape': []}}, 'uid': '0671598c-43b3-4edb-88bd-3463597c5800'}]
start 	
beamline_id 	CSX
config 	
group 	
owner 	xf23id1
project 	
sample 	
scan_id 	50934
time 	3 months ago (2015-07-27T09:13:34.085378)
time_as_datetime 	2015-07-27 09:13:34.085000
uid 	85e04a15-1072-4714-814d-76f0ec9edb87
stop 	
exit_status 	success
reason 	
run_start 	85e04a15-1072-4714-814d-76f0ec9edb87
time 	3 months ago (2015-07-27T09:13:59.608164)
time_as_datetime 	2015-07-27 09:13:59.608000
uid 	0fbef8a3-735b-47f6-a8fe-cb51bcc1d397
In [17]:

fn = '{filename}.h5'.format(filename=FILENAME)
if os.path.isfile(fn):
    if OVERWRITE:
        os.remove(fn)
    else:
        raise Exception("That file already exists. Set OVERWRITE = True if you want to overwrite.")
export([h], fn)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-3e3ba28a197d> in <module>()
      5     else:
      6         raise Exception("That file already exists. Set OVERWRITE = True if you want to overwrite.")
----> 7 export([h], fn)

NameError: name 'export' is not defined

**Comment by danielballan** [comment]
Suitcase does not seem to be installed. The important error here is, "No
module named suitcase". I suspect it is missing from the analysis env (cc
@ericdill). I will install it by the end of the day.

**Comment by ambarb** [comment]
Thanks. Please let me know when it is ready.

**Comment by danielballan** [comment]
Ready!

**Comment by tacaswell** [comment]
Closing this as it was addressed by installing the missing conda package
